//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleNot.Resource {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class langres {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal langres() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ConsoleNot.Lang.langres", typeof(langres).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Commands_Help_ {
            get {
                return ResourceManager.GetString("Commands_Help_", resourceCulture);
            }
        }
        
        internal static string There_is_no_ {
            get {
                return ResourceManager.GetString("There_is_no_", resourceCulture);
            }
        }
        
        internal static string Enter_Title {
            get {
                return ResourceManager.GetString("Enter_Title", resourceCulture);
            }
        }
        
        internal static string Enter_Description {
            get {
                return ResourceManager.GetString("Enter_Description", resourceCulture);
            }
        }
        
        internal static string Sorry_OS {
            get {
                return ResourceManager.GetString("Sorry_OS", resourceCulture);
            }
        }
        
        internal static string Only_Numbers {
            get {
                return ResourceManager.GetString("Only_Numbers", resourceCulture);
            }
        }
        
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        internal static string Config_Error {
            get {
                return ResourceManager.GetString("Config_Error", resourceCulture);
            }
        }
        
        internal static string Server_Error {
            get {
                return ResourceManager.GetString("Server_Error", resourceCulture);
            }
        }
        
        internal static string Client_Exception {
            get {
                return ResourceManager.GetString("Client_Exception", resourceCulture);
            }
        }
        
        internal static string Enter_Port {
            get {
                return ResourceManager.GetString("Enter_Port", resourceCulture);
            }
        }
        
        internal static string Enter_IP {
            get {
                return ResourceManager.GetString("Enter_IP", resourceCulture);
            }
        }
        
        internal static string Notify_Ex {
            get {
                return ResourceManager.GetString("Notify_Ex", resourceCulture);
            }
        }
        
        internal static string Notification_End {
            get {
                return ResourceManager.GetString("Notification_End", resourceCulture);
            }
        }
        
        internal static string Program_auto_launch_linux {
            get {
                return ResourceManager.GetString("Program_auto_launch_linux", resourceCulture);
            }
        }
    }
}
