//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Lang {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class langres_ru {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal langres_ru() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Web.Lang.langres_ru", typeof(langres_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        internal static string NewNot {
            get {
                return ResourceManager.GetString("NewNot", resourceCulture);
            }
        }
        
        internal static string Index_Title {
            get {
                return ResourceManager.GetString("Index_Title", resourceCulture);
            }
        }
        
        internal static string Index_Description {
            get {
                return ResourceManager.GetString("Index_Description", resourceCulture);
            }
        }
        
        internal static string Index_Delay {
            get {
                return ResourceManager.GetString("Index_Delay", resourceCulture);
            }
        }
        
        internal static string Index_Iterations {
            get {
                return ResourceManager.GetString("Index_Iterations", resourceCulture);
            }
        }
        
        internal static string Notifications_Notifications {
            get {
                return ResourceManager.GetString("Notifications_Notifications", resourceCulture);
            }
        }
        
        internal static string Notifications_HaveNot {
            get {
                return ResourceManager.GetString("Notifications_HaveNot", resourceCulture);
            }
        }
        
        internal static string _Layout_WebSite {
            get {
                return ResourceManager.GetString("_Layout_WebSite", resourceCulture);
            }
        }
        
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        internal static string Notifications_Edit {
            get {
                return ResourceManager.GetString("Notifications_Edit", resourceCulture);
            }
        }
        
        internal static string Notifications_Delete {
            get {
                return ResourceManager.GetString("Notifications_Delete", resourceCulture);
            }
        }
        
        internal static string Index_Submit {
            get {
                return ResourceManager.GetString("Index_Submit", resourceCulture);
            }
        }
        
        internal static string Notifications_HaveNot1 {
            get {
                return ResourceManager.GetString("Notifications_HaveNot1", resourceCulture);
            }
        }
        
        internal static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        internal static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        internal static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        internal static string There_is_no_ {
            get {
                return ResourceManager.GetString("There_is_no_", resourceCulture);
            }
        }
        
        internal static string Commands_Help_ {
            get {
                return ResourceManager.GetString("Commands_Help_", resourceCulture);
            }
        }
        
        internal static string ErrorMessage_Usr {
            get {
                return ResourceManager.GetString("ErrorMessage_Usr", resourceCulture);
            }
        }
    }
}
